version: '3.7'

volumes:
    minio_data: {}
    postgres_data: {}
    redis_data: {}

services:
  minio:
    image: minio/minio
    command: server /data
    volumes:
      - minio_data:/data
    env_file:
      - .env_minio
    ports:
      - 9000:9000
    restart: unless-stopped
  postgres:
    image: postgis/postgis:13-master
    environment:
      POSTGRES_PASSWORD: devpgpass888
      POSTGRES_DB: video_squeezer
    ports:
      - 5432:5432
    expose:
      - '5432'
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: "bitnami/redis:latest"
    env_file:
      - .env_redis
    environment:
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_AUTH_CLIENTS=no
      - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt
      - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key
      - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/ca.crt
      - REDIS_TLS_PORT=6379
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - 'redis_data:/bitnami/redis/data'
      - './redis_certs:/opt/bitnami/redis/certs'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

