global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'local_incidents_app'
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: https
    basic_auth:
      username: admin
      password: password
    tls_config:
        insecure_skip_verify: true
    static_configs:
      - targets: ['node:8443']



