# NGINX_HTTP_PORT=80 NGINX_HTTPS_PORT=443 myIp=`sh ../local_ip.sh` docker-compose -p local_incidents_nginx -f docker-compose.yaml up --build

version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443/tcp
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      - HOST_NODE_APP=${myIp}:8080
      - HOST_MONITORING_APP=${myIp}:8082
      - HOST_MINIO=${myIp}:9000
      - HOST_IMGPROXY=${myIp}:8081

    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_conf/common:/etc/nginx/conf.d/common:ro
      - ./nginx_conf/templates:/etc/nginx/templates:ro
      - ./nginx_log:/var/log/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ulimits:
      nproc: 65535
      nofile:
        soft: 110000
        hard: 150000
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"










